Continue refactoring file locations in the two containers. Also refactor variables so they're consistent. Set container names in PS1. Update docs.

diff --git a/server/bin/dz b/server/bin/dz
--- a/server/bin/dz
+++ b/server/bin/dz
@@ -10,7 +10,7 @@ mkdir -p ${SERVER_PROFILE}/battleye
 # Server configuration file
 SERVER_CFG_FILE="serverDZ.cfg"
 SERVER_CFG_DST="${SERVER_PROFILE}/${SERVER_CFG_FILE}"
-SERVER_CFG_SRC="${CFG_SRC_FILES}/${SERVER_CFG_FILE}"
+SERVER_CFG_SRC="${FILES}/${SERVER_CFG_FILE}"
 
 # Command line parameters except mod, as that is handled separately.
 parameters="-config=${SERVER_CFG_DST} -port=${port} -freezecheck -BEpath=${SERVER_PROFILE}/battleye -profiles=${SERVER_PROFILE} -nologs"
@@ -19,7 +19,7 @@ parameters="-config=${SERVER_CFG_DST} -port=${port} -freezecheck -BEpath=${SERVE
 SERVER_INSTALL_FILE="${SERVER_FILES}/DayZServer"
 
 # Workshop. This file will store metadata about what mods are in use in this server instance
-WORKSHOP_CFG="${HOME}/workshop.cfg"
+WORKSHOP_CFG="${SERVER_PROFILE}/workshop.cfg"
 if [ ! -f "${WORKSHOP_CFG}" ]
 then
 	touch "${WORKSHOP_CFG}"
@@ -29,7 +29,7 @@ INSTALLED_MODS="${SERVER_FILES}/workshop.cfg"
 
 # An array to store Workshop items. Each element contains the mod's ID, name, and state (active or not).
 declare -a workshopID
-workshopfolder="${SERVER_FILES}/steamapps/workshop/content/${release_client_appid}"
+WORKSHOP_DIR="${SERVER_FILES}/steamapps/workshop/content/${release_client_appid}"
 
 # Backups
 BACKUP_DIR="${HOME}/backup"
@@ -63,6 +63,62 @@ ${default}"
   exit 1
 }
 
+loadconfig(){
+	if [ ! -f "${SERVER_INSTALL_FILE}" ]
+	then
+		echo
+		echo -e "The DayZ server files are not installed. Run '${green}docker-compose run --rm main dayzserver install${default}'"
+		echo
+		exit 1
+	fi
+	# Handle the initial server configuration file
+	if [ ! -f ${SERVER_CFG_DST} ]
+	then
+		echo "Creating initial server configuration file"
+		cp "${SERVER_CFG_SRC}" "${SERVER_CFG_DST}"
+	fi
+	# battleye config and rconpassword setup
+	# The server creates a new file from this file, which it then uses.
+	# Let's make sure to delete it first
+	BE_SERVER_FILE="${SERVER_PROFILE}/battleye/beserver_x64.cfg"
+	ALT_BE_SERVER_FILE=$(find ${SERVER_PROFILE}/battleye -name "beserver_x64_active*")
+	if [ ! -f "${BE_SERVER_FILE}" ] && [ ! -f "${ALT_BE_SERVER_FILE}" ]
+	then
+		passwd=$(openssl rand -base64 8 | tr -dc 'A-Za-z0-9')
+		if [ "${passwd}" == "" ]
+		then
+			passwd=$(< /dev/urandom tr -dc 'A-Za-z0-9' | head -c10)
+		fi
+		if [ "${passwd}" == "" ]
+		then
+			printf "[ ${red}FAIL${default} ] Could not generate a passwort for RCON!\nOpen the Battleye config with 'dayzserver rcon'."
+			exit 1
+		else
+			cat > "${BE_SERVER_FILE}" <<EOF
+RConPassword ${passwd}
+RestrictRCon 0
+RConPort ${rcon_port}
+EOF
+		fi
+		printf "[ ${cyan}INFO${default} ] New RCON password: ${yellow}${passwd}${default}\n"
+	else
+		if [ -f "${BE_SERVER_FILE}" ]
+		then
+			FILE="${BE_SERVER_FILE}"
+		elif [ -f "${ALT_BE_SERVER_FILE}" ]
+		then
+			FILE="${ALT_BE_SERVER_FILE}"
+		fi
+		passwd=$(grep RConPassword ${FILE} | awk '{print $2}')
+#		printf "[ ${cyan}INFO${default} ] Using existing RCON password: ${yellow}${passwd}${default}\n"
+	fi
+	cp /usr/local/py3rcon/configexample.json ~/py3rcon.config.json
+	jq --arg port 2303 --arg rcon_password b0fNIBVfkM \
+		'.logfile="py3rcon.log" | .loglevel=0 | .server.port=$port | .server.rcon_password=$rcon_password | del(.repeatMessage)' \
+		/usr/local/py3rcon/configexample.json \
+		> ~/py3rcon.config.json
+}
+
 # Manage the mod symlink
 symlink(){
 	W=${1}
@@ -70,7 +126,7 @@ symlink(){
 	NAME=${3}
 	if [ ! -L "${SERVER_FILES}/@${NAME}" ] && [[ ${W} = 1 ]]
 	then
-		ln -sv ${workshopfolder}/${ID} "${SERVER_FILES}/@${NAME}"
+		ln -sv ${WORKSHOP_DIR}/${ID} "${SERVER_FILES}/@${NAME}"
 	elif [[ "${W}" = "0" ]]
 	then
 		rm -vf "${SERVER_FILES}/@${NAME}"
@@ -202,18 +258,18 @@ get_mod_id_by_index(){
 # Get mod name by ID or index
 get_mod_name(){
 	# Check for an ID
-	if [ -d "${workshopfolder}/${1}" ]
+	if [ -d "${WORKSHOP_DIR}/${1}" ]
 	then
 		ID=${1}
 	else
 		ID=$(get_mod_id_by_index ${1})
 	fi
-	if ! [ -d "${workshopfolder}/${ID}" ]
+	if ! [ -d "${WORKSHOP_DIR}/${ID}" ]
 	then
 		echo "Mod ID ${1} doesn't exist" >&2
 		exit 1
 	fi
-	NAME=$(grep name ${workshopfolder}/${ID}/meta.cpp | cut -d '"' -f2 | sed -r 's/\s+//g')
+	NAME=$(grep name ${WORKSHOP_DIR}/${ID}/meta.cpp | cut -d '"' -f2 | sed -r 's/\s+//g')
 	echo ${NAME}
 }
 
@@ -240,35 +296,6 @@ activate(){
 		echo -e "Mod id ${ID} - ${COLOR}${MODNAME}${default} - is already ${WW}active"
 	fi
 	list
-}
-
-# List available mods
-list(){
-	get_installed_mods
-
-	if [[ "${workshopID[@]}" = "" ]]
-	then
-		return
-	fi
-	X=1
-	spaces="                        "
-	echo -e "\n     ID         Name                      Active URL                                                                Size"
-	echo "------------------------------------------------------------------------------------------------------------------------"
-	for i in "${workshopID[@]}"
-	do
-		ID=$(echo ${i} | cut -d: -f1)
-		NAME=$(echo ${i} | cut -d: -f2)
-		ACTIVE=$(echo ${i} | cut -d: -f3)
-		SIZE=$(du -sh ${SERVER_FILES}/steamapps/workshop/content/221100/${ID} | awk '{print $1}')
-		if [[ ${ACTIVE} = "1" ]]
-		then
-			C="${green}"
-		else
-			C="${red}"
-		fi
-		printf "${C}%.3d  %s %.23s  %s %s      https://steamcommunity.com/sharedfiles/filedetails/?id=%s  %s${default}\n" ${X} ${ID} "${NAME}" "${spaces:${#NAME}+1}" ${ACTIVE} ${ID} ${SIZE}
-		X=$((X+1))
-	done
 }
 
 # Assemble the mod command line
@@ -301,15 +328,15 @@ checkXML(){
 			if echo ${!xml} | grep -q http
 			then
 				echo "${NAME} file is remote, downloading..."
-				curl -o ${workshopfolder}/${1}/${NAME}.xml ${!xml}
+				curl -o ${WORKSHOP_DIR}/${1}/${NAME}.xml ${!xml}
 			else
 				echo "${NAME} file is in the mod, copying..."
-				cp -vf ${!xml} ${workshopfolder}/${1}/${NAME}.xml
+				cp -vf ${!xml} ${WORKSHOP_DIR}/${1}/${NAME}.xml
 			fi
 		done
 #	else
 		# See if this mod has a types.xml in the "standard" locations
-#		for path in "${workshopfolder}/${1}/extras" "${workshopfolder}/${1}"
+#		for path in "${WORKSHOP_DIR}/${1}/extras" "${WORKSHOP_DIR}/${1}"
 #		do
 #			if [ -f "${path}/types.xml" ]
 #			then
@@ -368,7 +395,6 @@ status(){
 	fi
 	# Number of mods plus the list denoting on or off
 	echo -ne "
-Logged in to Steam: ${LOGGED_IN} ${ANONYMOUS}
 Server files installed: ${INSTALLED}"
 	if [[ "${INSTALLED}" = "${NO}" ]]
 	then
