Continue splitting up the functionality. Only put functions and files that pertain to the container and/or volume. Set forceSameBuild = 0 because the release build we have, while it works, reports a few revisions behind. WIP getting all this working again.

diff --git a/web/bin/dz b/web/bin/dz
--- a/web/bin/dz
+++ b/web/bin/dz
@@ -13,6 +13,8 @@ fi
 declare -a workshopID
 workshopfolder="${SERVER_FILES}/steamapps/workshop/content/${release_client_appid}"
 
+workshoplist=""
+
 # Functions
 
 # Usage
@@ -34,6 +36,60 @@ Options and arguments:
   u|update - Update the server files
 ${default}"
   exit 1
+}
+
+# Ensures all is installed and ready before allowing operations that depends on things being ready.
+# Installs the initial server config file from its template.
+# Handles the importing of changes to that template.
+# Installs the initial Battleye RCON config.
+loadconfig(){
+#	check_install
+	# Handle the initial server configuration file
+	if [ ! -f ${SERVER_CFG_DST} ]
+	then
+		echo "Creating initial server configuration file"
+		cp "${SERVER_CFG_SRC}" "${SERVER_CFG_DST}"
+	fi
+	# battleye config and rconpassword setup
+	# The server creates a new file from this file, which it then uses.
+	# Let's make sure to delete it first
+	BE_SERVER_FILE="${SERVER_FILES}/battleye/beserver_x64.cfg"
+	ALT_BE_SERVER_FILE=$(find ${SERVER_FILES}/battleye -name "beserver_x64_active*")
+	if [ ! -f "${BE_SERVER_FILE}" ] && [ ! -f "${ALT_BE_SERVER_FILE}" ]
+	then
+		passwd=$(openssl rand -base64 8 | tr -dc 'A-Za-z0-9')
+		if [ "${passwd}" == "" ]
+		then
+			passwd=$(< /dev/urandom tr -dc 'A-Za-z0-9' | head -c10)
+		fi
+		if [ "${passwd}" == "" ]
+		then
+			printf "[ ${red}FAIL${default} ] Could not generate a passwort for RCON!\nOpen the Battleye config with 'dayzserver rcon'."
+			exit 1
+		else
+			cat > "${BE_SERVER_FILE}" <<EOF
+RConPassword ${passwd}
+RestrictRCon 0
+RConPort ${rcon_port}
+EOF
+		fi
+		printf "[ ${cyan}INFO${default} ] New RCON password: ${yellow}${passwd}${default}\n"
+	else
+		if [ -f "${BE_SERVER_FILE}" ]
+		then
+			FILE="${BE_SERVER_FILE}"
+		elif [ -f "${ALT_BE_SERVER_FILE}" ]
+		then
+			FILE="${ALT_BE_SERVER_FILE}"
+		fi
+		passwd=$(grep RConPassword ${FILE} | awk '{print $2}')
+#		printf "[ ${cyan}INFO${default} ] Using existing RCON password: ${yellow}${passwd}${default}\n"
+	fi
+	cp /usr/local/py3rcon/configexample.json ~/py3rcon.config.json
+	jq --arg port 2303 --arg rcon_password b0fNIBVfkM \
+		'.logfile="py3rcon.log" | .loglevel=0 | .server.port=$port | .server.rcon_password=$rcon_password | del(.repeatMessage)' \
+		/usr/local/py3rcon/configexample.json \
+		> ~/py3rcon.config.json
 }
 
 # Handle the Steam login information.
@@ -149,29 +205,34 @@ modupdate(){
 
 # List mods
 list(){
-	# The state may have changed since we started
-	get_mods
+	mapfile -t workshopID < "${WORKSHOP_CFG}"
+	workshoplist=""
+	for i in "${workshopID[@]}"
+	do
+		ID=$(echo ${i} | cut -d: -f1)
+		workshoplist+=" +workshop_download_item "${release_client_appid}" "${ID}
+	done
 	if [[ "${workshopID[@]}" = "" ]]
 	then
 		return
 	fi
 	X=1
 	spaces="                        "
-	echo -e "\n     ID         Name                      Active URL                                                                Size"
+	echo -e "\n     ID         Name                             URL                                                                Size"
 	echo "------------------------------------------------------------------------------------------------------------------------"
 	for i in "${workshopID[@]}"
 	do
 		ID=$(echo ${i} | cut -d: -f1)
 		NAME=$(echo ${i} | cut -d: -f2)
-		ACTIVE=$(echo ${i} | cut -d: -f3)
+#		ACTIVE=$(echo ${i} | cut -d: -f3)
 		SIZE=$(du -sh ${SERVER_FILES}/steamapps/workshop/content/221100/${ID} | awk '{print $1}')
-		if [[ ${ACTIVE} = "1" ]]
-		then
+#		if [[ ${ACTIVE} = "1" ]]
+#		then
 			C="${green}"
-		else
-			C="${red}"
-		fi
-		printf "${C}%.3d  %s %.23s  %s %s      https://steamcommunity.com/sharedfiles/filedetails/?id=%s  %s${default}\n" ${X} ${ID} "${NAME}" "${spaces:${#NAME}+1}" ${ACTIVE} ${ID} ${SIZE}
+#		else
+#			C="${red}"
+#		fi
+		printf "${C}%.3d  %s %.23s    %s      https://steamcommunity.com/sharedfiles/filedetails/?id=%s  %s${default}\n" ${X} ${ID} "${NAME}" "${spaces:${#NAME}+1}" ${ID} ${SIZE}
 		X=$((X+1))
 	done
 }
@@ -223,8 +284,6 @@ C=${1}
 shift || {
 	usage
 }
-
-get_mods
 
 case "${C}" in
 	add)
