Prevent problems when we can't get metadata, usually because meta.cpp doesn't exist. Some mods don't seem to have one.

diff --git a/files/bin/dz-common b/files/bin/dz-common
--- a/files/bin/dz-common
+++ b/files/bin/dz-common
@@ -97,6 +97,11 @@ get_mod_name(){
 		exit 1
 	fi
 	NAME=$(grep name ${WORKSHOP_DIR}/${1}/meta.cpp | cut -d '"' -f2 | tr -cd [:alnum:])
+	if [[ ${NAME} = "" ]]
+	then
+		echo "Could not get metadata. See above. Exiting..."
+		exit 1
+	fi
 	echo -n ${NAME}
 }
 
